/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HTMLElement {
  outerHTML: string
  get innerHTML(): string
  get text(): string
  get id(): string | null
  get tagName(): string
  getAttribute(name: string): string | null
  get attributes(): Record<string, string>
  get className(): string
  get classList(): Array<string>
  selectFirst(options: SelectFirstOptions): HTMLElement | null
  selectMany(options: SelectManyOptions): Array<HTMLElement>
  get firstChild(): HTMLElement | null
  get lastChild(): HTMLElement | null
  toString(): string
}

export declare class HTMLParser {
  constructor(content: string)
  selectFirst(options: SelectFirstOptions): HTMLElement | null
  selectMany(options: SelectManyOptions): Array<HTMLElement>
}

export declare function css(query: string): QueryConfig

export declare function parse(content: string): HTMLParser

export interface QueryConfig {
  query: string
  type: QueryType
}

export declare const enum QueryType {
  CSS = 0,
  XPath = 1
}

export interface SelectFirstOptions {
  query: QueryConfig
}

export interface SelectManyOptions {
  query: QueryConfig
  limit?: number
}

export declare function xpath(query: string): QueryConfig
