/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HtmlElement {
  outerHTML: string
  get text(): string
  get id(): string | null
  get tagName(): string
  getAttribute(name: string): string | null
  get attributes(): Record<string, string>
  get className(): string
  get classList(): Array<string>
  selectFirst(options: SelectFirstOptions): HtmlElement | null
  selectMany(options: SelectManyOptions): Array<HtmlElement>
}

export declare class HtmlParser {
  constructor(content: string)
  selectFirst(options: SelectFirstOptions): HtmlElement | null
  selectMany(options: SelectManyOptions): Array<HtmlElement>
}

export declare function css(query: string): QueryConfig

export interface QueryConfig {
  query: string
  type: QueryType
}

export declare const enum QueryType {
  CSS = 0,
  XPath = 1
}

export interface SelectFirstOptions {
  query: QueryConfig
}

export interface SelectManyOptions {
  query: QueryConfig
  limit?: number
}

export declare function xpath(query: string): QueryConfig
